service: ping-me

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python2.7

functions:
  currentTime:
    handler: handler.ping
    events:
      - http:
          path: ping
          method: get
