service: SimplePush

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python2.7

functions:
  currentTime:
    handler: handler.push
    events:
      - http:
          path: push
          method: get
    environment:
      PUSHBULLET_API_KEY: ${env:PUSHBULLET_API_KEY}
      AUTH_KEY: ${env:AUTH_KEY}
